export const CONNECT_PENDING = 'CONNECT_PENDING';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_FAILURE = 'CONNECT_FAILURE';

export const DISCONNECT_PENDING = 'DISCONNECT_PENDING';
export const DISCONNECT_SUCCESS = 'DISCONNECT_SUCCESS';
export const DISCONNECT_FAILURE = 'DISCONNECT_FAILURE';
