export const SYMPTOM_ADD_PENDING = 'SYMPTOM_ADD_PENDING';
export const SYMPTOM_ADD_SUCCESS = 'SYMPTOM_ADD_SUCCESS';
export const SYMPTOM_ADD_FAILURE = 'SYMPTOM_ADD_FAILURE';

export const SYMPTOM_GET_PENDING = 'SYMPTOM_GET_PENDING';
export const SYMPTOM_GET_SUCCESS = 'SYMPTOM_GET_SUCCESS';
export const SYMPTOM_GET_FAILURE = 'SYMPTOM_GET_FAILURE';

export const SIGNAL_ADD_PENDING = 'SIGNAL_ADD_PENDING';
export const SIGNAL_ADD_SUCCESS = 'SIGNAL_ADD_SUCCESS';
export const SIGNAL_ADD_FAILURE = 'SIGNAL_ADD_FAILURE';

export const SIGNAL_GET_PENDING = 'SIGNAL_GET_PENDING';
export const SIGNAL_GET_SUCCESS = 'SIGNAL_GET_SUCCESS';
export const SIGNAL_GET_FAILURE = 'SIGNAL_GET_FAILURE';
