export const CONTACT_REGISTER_PENDING = 'CONTACT_REGISTER_PENDING';
export const CONTACT_REGISTER_SUCCESS = 'CONTACT_REGISTER_SUCCESS';
export const CONTACT_REGISTER_FAILURE = 'CONTACT_REGISTER_FAILURE';

export const CONTACT_DELETE_PENDING = 'CONTACT_DELETE_PENDING';
export const CONTACT_DELETE_SUCCESS = 'CONTACT_DELETE_SUCCESS';
export const CONTACT_DELETE_FAILURE = 'CONTACT_DELETE_FAILURE';

export const CONTACT_GET_PENDING = 'CONTACT_GET_PENDING';
export const CONTACT_GET_SUCCESS = 'CONTACT_GET_SUCCESS';
export const CONTACT_GET_FAILURE = 'CONTACT_GET_FAILURE';